name: Deploy Flow
on:
  workflow_dispatch:
  push:
    tags:
      - 'v**'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: print
        run: echo "DONE!!"
