name: learn-github-actions
on: [push, workflow_dispatch]
  
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "DISTRIBUTION_NAME=${{ github.head_ref }}" >> $GITHUB_ENV
        if: ${{ github.event_name == 'pull_request' }}
      - run: echo "DISTRIBUTION_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
      - run: echo "name=$DISTRIBUTION_NAME"
