name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "DISTRIBUTION_NAME=${{ github.head_ref }}" >> $GITHUB_ENV
        if: ${{ github.event_name == 'pull_request' }}
      - run: echo "DISTRIBUTION_NAME=${{ steps.extract_branch.outputs.branch }}" >> $GITHUB_ENV
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
      - run: echo "name=$DISTRIBUTION_NAME"
