name: learn-github-actions
on: [push, workflow_dispatch]
  
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "${GITHUB_REF#refs/heads/}" # PRの番号が取得されてしまいます
      - run: echo "${GITHUB_HEAD_REF}"
      - run: echo "${{ github.ref }}"
      - run: echo "DISTRIBUTION_NAME=${GITHUB_HEAD_REF}" >> $GITHUB_ENV
        if: ${{ github.event_name == 'pull_request' }}
      - run: echo "DISTRIBUTION_NAME=$(echo ${$GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
      - run: echo "name=$DISTRIBUTION_NAME"
